### ISSUE TITLE
Some sort of memory error in random number generation

### ISSUE THREAD

**Issue by Keno** [rfourquet/BitFloats.jl#1] opened 2019-08-29 16:06 UTC
```
julia> xs = rand(Float80, 10000)
ERROR: ReadOnlyMemoryError()
Stacktrace:
 [1] setindex! at ./array.jl:780 [inlined]
 [2] rand! at /Users/kfischer/Projects/julia-doublecheck/usr/share/julia/stdlib/v1.4/Random/src/Random.jl:268 [inlined]
 [3] rand! at /Users/kfischer/Projects/julia-doublecheck/usr/share/julia/stdlib/v1.4/Random/src/Random.jl:264 [inlined]
 [4] rand(::Random.MersenneTwister, ::Type{Float80}, ::Tuple{Int64}) at /Users/kfischer/Projects/julia-doublecheck/usr/share/julia/stdlib/v1.4/Random/src/Random.jl:285
 [5] rand at /Users/kfischer/Projects/julia-doublecheck/usr/share/julia/stdlib/v1.4/Random/src/Random.jl:286 [inlined]
 [6] rand(::Type{Float80}, ::Int64) at /Users/kfischer/Projects/julia-doublecheck/usr/share/julia/stdlib/v1.4/Random/src/Random.jl:289
 [7] top-level scope at REPL[2]:1
```

**Comment by rfourquet** [comment] 2019-09-17 08:58
I get a segmentation fault. But I don't think this is related to RNG, when I try to write a fixed value to each position of `Array{Float80}(undef, 10000)`, I get a `corrupted size vs. prev_size` error followed by an abort signal sent. I believe it's caused by a Julia bug with arrays of `eltype` of size not-a-power-of-two, cf. https://github.com/JuliaLang/julia/issues/29053.

**Comment by rfourquet** [comment] 2019-10-02 08:30
Fixed by https://github.com/JuliaLang/julia/pull/33283.

**Closed as completed by rfourquet** 2019-10-02 08:30 UTC
